parameters:
    sylius.twig.extension.resource.pagination_template: 'ModernFactoryResourcesBundle:Twig:paginate.html.twig'
    sylius.twig.extension.resource.sorting_template: 'ModernFactoryResourcesBundle:Twig:sorting.html.twig'

services:
    sylius.controller.parameters:
        class: ModernFactory\ResourcesBundle\Controller\Parameters
    sylius.twig.extension.resource:
        class: ModernFactory\ResourcesBundle\Twig\ResourceExtension
        tags:
            - { name: twig.extension }
            - { name: kernel.event_listener, event: kernel.request, method: fetchRequest }
        arguments: ['@router', '@sylius.controller.parameters', '%sylius.twig.extension.resource.pagination_template%', '%sylius.twig.extension.resource.sorting_template%']
