parameters:
    resources_bundle.twig.extension.resource.pagination_template: 'ModernFactoryResourcesBundle:Twig:paginate.html.twig'
    resources_bundle.twig.extension.resource.sorting_template: 'ModernFactoryResourcesBundle:Twig:sorting.html.twig'

services:
    resources_bundle.controller.parameters:
        class: ModernFactory\ResourcesBundle\Controller\Parameters
    resources_bundle.twig.extension.resource:
        class: ModernFactory\ResourcesBundle\Twig\ResourceExtension
        tags:
            - { name: twig.extension }
            - { name: kernel.event_listener, event: kernel.request, method: fetchRequest }
        arguments:
            - '@router'
            - '@resources_bundle.controller.parameters'
            - '%resources_bundle.twig.extension.resource.pagination_template%'
            - '%resources_bundle.twig.extension.resource.sorting_template%'
